/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  // Fully static site: `next build` writes plain HTML/JSON into out/ and
  // Vercel serves those files as-is — no functions, no ISR, the same model as
  // pumpkinpatchesnearme.com. Redirects and response headers can't run in a
  // static export, so they live in vercel.json (generated by
  // scripts/generate-vercel-json.ts).
  output: 'export',
  images: {
    // No image optimizer without a server; photos are served from their
    // source URLs as-is.
    unoptimized: true,
    remotePatterns: [
      { protocol: 'https', hostname: 'lh3.googleusercontent.com' },
      { protocol: 'https', hostname: 'lh4.googleusercontent.com' },
      { protocol: 'https', hostname: 'lh5.googleusercontent.com' },
      { protocol: 'https', hostname: 'lh6.googleusercontent.com' },
      { protocol: 'https', hostname: 'maps.googleapis.com' },
      { protocol: 'https', hostname: 'streetviewpixels-pa.googleapis.com' },
      { protocol: 'https', hostname: 'm.media-amazon.com' },
    ],
  },
}

export default nextConfig
