import type { Metadata } from 'next'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import FindHubSearch from './find-hub-search'
import { CAPITAL_CITIES } from '@/lib/capital-cities'
import { MAJOR_CITIES } from '@/lib/major-cities-list'
import { getCities } from '@/lib/restaurants'
import { STATE_CODE_TO_NAME } from '@/lib/state-lookups'

function titleCase(slug: string): string {
  return slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
}

// Build the full list of /find/{city}-{state} pages, grouped by state — the
// same set generated by the [cityState] route (DB cities + capitals + majors).
function getCityFindPagesByState(): Array<{ stateName: string; stateCode: string; cities: Array<{ param: string; city: string }> }> {
  const byState = new Map<string, Map<string, string>>() // stateCode → (param → city)

  const add = (stateCode: string, param: string, city: string) => {
    const sc = stateCode.toUpperCase()
    if (!byState.has(sc)) byState.set(sc, new Map())
    const m = byState.get(sc)!
    if (!m.has(param)) m.set(param, city)
  }

  // DB cities with their own page (2+ listings)
  for (const c of getCities()) {
    add(c.stateCode, `${c.citySlug}-${c.stateCode.toLowerCase()}`, c.city)
  }
  // State capitals
  for (const c of CAPITAL_CITIES) {
    add(c.stateCode, c.param, c.city)
  }
  // Major cities across all 50 states
  for (const c of MAJOR_CITIES) {
    add(c.stateCode, `${c.city.toLowerCase().trim().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')}-${c.stateCode.toLowerCase()}`, c.city)
  }

  return Array.from(byState.entries())
    .map(([stateCode, m]) => ({
      stateCode,
      stateName: STATE_CODE_TO_NAME[stateCode] ?? stateCode,
      cities: Array.from(m.entries())
        .map(([param, city]) => ({ param, city: city || titleCase(param.replace(/-[a-z]{2}$/, '')) }))
        .sort((a, b) => a.city.localeCompare(b.city)),
    }))
    .sort((a, b) => a.stateName.localeCompare(b.stateName))
}

export const metadata: Metadata = {
  title: 'Find Ramen Near Me | Browse by Filter | RamenNearYou',
  description: 'Find ramen restaurants near you filtered by what matters — open late, open now, tonkotsu, vegan, spicy, and more.',
  alternates: { canonical: 'https://www.ramennearyou.com/find' },
}

const CATEGORIES = [
  {
    heading: 'By Hours',
    pages: [
      { href: '/find/ramen-open-now', label: 'Ramen Open Now Near Me' },
      { href: '/find/ramen-open-late', label: 'Ramen Open Late Near Me' },
      { href: '/find/ramen-lunch', label: 'Ramen for Lunch Near Me' },
      { href: '/find/ramen-open-early', label: 'Ramen Open Early Near Me' },
      { href: '/find/ramen-open-weekends', label: 'Ramen Open on Weekends Near Me' },
      { href: '/find/ramen-open-july-4th', label: 'Ramen Open on Independence Day' },
      { href: '/find/ramen-open-24-hours', label: 'Ramen Open 24 Hours Near Me' },
    ],
  },
  {
    heading: 'By Amenities & Features',
    pages: [
      { href: '/find/ramen-delivery', label: 'Ramen Delivery Near Me' },
      { href: '/find/ramen-outdoor-seating', label: 'Ramen With Outdoor Seating Near Me' },
      { href: '/find/ramen-reservations', label: 'Ramen With Reservations Near Me' },
      { href: '/find/ramen-full-bar', label: 'Ramen With a Full Bar Near Me' },
      { href: '/find/ramen-family-friendly', label: 'Family-Friendly Ramen Near Me' },
      { href: '/find/ramen-wheelchair-accessible', label: 'Wheelchair Accessible Ramen Near Me' },
      { href: '/find/ramen-free-parking', label: 'Ramen With Free Parking Near Me' },
      { href: '/find/ramen-hidden-gems', label: 'Hidden Gem Ramen Near Me' },
      { href: '/find/new-ramen-near-me', label: 'New Ramen Places Near Me' },
      { href: '/find/5-star-ramen', label: '5 Star Ramen Restaurants Near Me' },
    ],
  },
  {
    heading: 'By Broth',
    pages: [
      { href: '/find/tonkotsu-ramen', label: 'Tonkotsu Ramen Near Me' },
      { href: '/find/miso-ramen', label: 'Miso Ramen Near Me' },
      { href: '/find/ramen-spicy-miso-near-me', label: 'Ramen Spicy Miso Near Me' },
      { href: '/find/shoyu-ramen', label: 'Shoyu Ramen Near Me' },
      { href: '/find/shio-ramen', label: 'Shio Ramen Near Me' },
      { href: '/find/chicken-ramen', label: 'Chicken Ramen Near Me' },
      { href: '/find/chicken-katsu-ramen', label: 'Chicken Katsu Ramen Near Me' },
      { href: '/find/beef-ramen', label: 'Beef Ramen Near Me' },
      { href: '/find/fish-ramen-near-me', label: 'Fish Ramen Near Me' },
      { href: '/find/black-garlic-ramen', label: 'Black Garlic Ramen Near Me' },
    ],
  },
  {
    heading: 'By Style',
    pages: [
      { href: '/find/tsukemen', label: 'Tsukemen Near Me' },
      { href: '/find/mazemen', label: 'Mazemen Near Me' },
      { href: '/find/tantanmen', label: 'Tantanmen Near Me' },
      { href: '/find/thick-noodle-ramen', label: 'Thick Noodle Ramen Near Me' },
      { href: '/find/thin-noodle-ramen', label: 'Thin Noodle Ramen Near Me' },
      { href: '/find/hand-pulled-ramen', label: 'Hand Pulled Ramen Near Me' },
      { href: '/find/rich-ramen', label: 'Rich & Creamy Ramen Near Me' },
      { href: '/find/light-ramen', label: 'Light & Clean Ramen Near Me' },
    ],
  },
  {
    heading: 'By Spice',
    pages: [
      { href: '/find/spicy-ramen', label: 'Spicy Ramen Near Me' },
      { href: '/find/extra-spicy-ramen', label: 'Extra Spicy Ramen Near Me' },
    ],
  },
  {
    heading: 'By Diet & Price',
    pages: [
      { href: '/find/vegan-ramen', label: 'Vegan Ramen Near Me' },
      { href: '/find/vegetarian-ramen', label: 'Vegetarian Ramen Near Me' },
      { href: '/find/cheap-ramen', label: 'Ramen Under $15 Near Me' },
    ],
  },
  {
    heading: 'By Occasion',
    pages: [
      { href: '/find/ramen-date-night', label: 'Date Night Ramen Near Me' },
      { href: '/find/ramen-bars', label: 'Ramen Bars Near Me' },
      { href: '/find/ramen-restaurants', label: 'Ramen Restaurants Near Me' },
      { href: '/find/ramen-shop', label: 'Ramen Shop Near Me' },
      { href: '/find/ramen-karaoke-bar', label: 'Ramen Karaoke Bar Near Me' },
      { href: '/find/ramen-sushi-near-me', label: 'Ramen and Sushi Near Me' },
      { href: '/find/sushi-near-me', label: 'Sushi Near Me' },
      { href: '/find/lo-mein-near-me', label: 'Lo Mein Near Me' },
      { href: '/find/ramen-delivery', label: 'Ramen Delivery Near Me' },
    ],
  },
  {
    heading: 'By Origin & Authenticity',
    pages: [
      { href: '/find/japanese-ramen', label: 'Japanese Ramen Near Me' },
      { href: '/find/authentic-ramen', label: 'Authentic Ramen Near Me' },
      { href: '/find/traditional-ramen', label: 'Traditional Ramen Near Me' },
      { href: '/find/hokkaido-ramen', label: 'Hokkaido Ramen Near Me' },
      { href: '/find/fresh-ramen', label: 'Fresh Ramen Noodles Near Me' },
    ],
  },
  {
    heading: 'By Brand',
    pages: [
      { href: '/find/jinya-ramen', label: 'Jinya Ramen Near Me' },
      { href: '/find/ippudo-ramen', label: 'Ippudo Ramen Near Me' },
      { href: '/find/ichiran-ramen', label: 'Ichiran Ramen Near Me' },
      { href: '/find/lanzhou-ramen', label: 'Lanzhou Ramen Near Me' },
    ],
  },
]

export default function FindHubPage() {
  const cityPagesByState = getCityFindPagesByState()
  const totalCityPages = cityPagesByState.reduce((s, st) => s + st.cities.length, 0)

  return (
    <main className="min-h-screen bg-[#F5F4F0]">
      <Navbar />
      <div className="pt-24 pb-16 max-w-2xl mx-auto px-4 sm:px-6">
        <h1 className="font-serif text-3xl font-bold text-[#1E2026] mb-2">Find Ramen Near Me</h1>
        <p className="text-[#6B6862] text-sm mb-6">
          Browse ramen restaurants filtered by what you need right now.
        </p>

        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="https://www.downtoearth.org/sites/default/files/styles/max_800x800/public/images/blog/Ramen.jpg?itok=dmLVfPas"
          alt="A bowl of ramen topped with chashu, soft-boiled egg, nori, and scallions"
          className="w-full h-48 sm:h-64 object-cover rounded-2xl mb-8"
          loading="lazy"
        />

        <FindHubSearch
          categories={CATEGORIES}
          cityPagesByState={cityPagesByState}
          totalCityPages={totalCityPages}
        />
      </div>
      <Footer />
    </main>
  )
}
