// SERVER-ONLY shared helpers for /find city + modifier pages. Imports the
// heavy restaurants dataset, so never import from a client component. The param
// format matches the /find/[cityState] route: "{citySlug}-{stateCodeLower}"
// (e.g. "dallas-tx").
import { getCities, getRestaurantsByCity } from './restaurants'
import { getSupplementListings } from './places-supplements'
import { STATE_CODE_TO_SLUG, STATE_CODE_TO_NAME } from './state-lookups'
import { CAPITAL_CITIES, CAPITAL_BY_PARAM } from './capital-cities'
import { MAJOR_CITIES_PARAMS } from './major-cities-list'

const MAJOR_SET = new Set(MAJOR_CITIES_PARAMS)

export function parseCityState(cityState: string | undefined): { citySlug: string; stateCode: string } | null {
  if (!cityState) return null
  const lastHyphen = cityState.lastIndexOf('-')
  if (lastHyphen < 1) return null
  const stateCode = cityState.slice(lastHyphen + 1).toUpperCase()
  const citySlug = cityState.slice(0, lastHyphen)
  if (!STATE_CODE_TO_SLUG[stateCode]) return null
  return { citySlug, stateCode }
}

// City params with a dedicated find page: DB cities with 2+ listings, all state
// capitals, and major cities — the canonical set generated by /find/[cityState].
export function getFindCityParams(): Array<{ cityState: string }> {
  const dbParams = getCities()
    .filter(c => c.count >= 2)
    .map(c => `${c.citySlug}-${c.stateCode.toLowerCase()}`)
  const dbSet = new Set(dbParams)
  const capitalParams = CAPITAL_CITIES.filter(c => !dbSet.has(c.param)).map(c => c.param)
  const majorParams = MAJOR_CITIES_PARAMS.filter(p => !dbSet.has(p))
  const all = new Set([...dbParams, ...capitalParams, ...majorParams])
  return Array.from(all).map(cityState => ({ cityState }))
}

export interface ResolvedCity {
  citySlug: string
  stateCode: string
  stateSlug: string
  stateName: string
  cityName: string
  lat: number
  lng: number
  /** True when this is a real city we list (DB, supplements, capital, or major). */
  known: boolean
}

export function resolveFindCity(cityState: string | undefined): ResolvedCity | null {
  const parsed = parseCityState(cityState)
  if (!parsed) return null
  const { citySlug, stateCode } = parsed
  const stateSlug = STATE_CODE_TO_SLUG[stateCode]
  const stateName = STATE_CODE_TO_NAME[stateCode] ?? stateCode
  const dbRestaurants = getRestaurantsByCity(citySlug, stateSlug)
  const places = dbRestaurants.length === 0 ? getSupplementListings(citySlug, stateCode) : []
  const capital = CAPITAL_BY_PARAM[cityState!]
  const isMajor = MAJOR_SET.has(cityState!)
  const known = dbRestaurants.length > 0 || places.length > 0 || !!capital || isMajor
  const citySlugTitle = citySlug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
  const cityName = dbRestaurants[0]?.city ?? capital?.city ?? places[0]?.city ?? citySlugTitle
  const lat = capital?.lat ?? dbRestaurants.find(r => r.latitude)?.latitude ?? places.find(r => r.latitude)?.latitude ?? 39.5
  const lng = capital?.lng ?? dbRestaurants.find(r => r.longitude)?.longitude ?? places.find(r => r.longitude)?.longitude ?? -98.35
  return { citySlug, stateCode, stateSlug, stateName, cityName, lat, lng, known }
}
