/**
 * All major city params (e.g. "chicago-il") for use in generateStaticParams.
 * Computed from the same city list used by scripts/fetch-major-city-places.mjs.
 */

function slugify(str: string): string {
  return str.toLowerCase().trim().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
}

const MAJOR_CITIES = [
  // Alabama
  { city: 'Birmingham',    stateCode: 'AL' },
  { city: 'Huntsville',    stateCode: 'AL' },
  { city: 'Mobile',        stateCode: 'AL' },
  { city: 'Tuscaloosa',    stateCode: 'AL' },
  { city: 'Montgomery',    stateCode: 'AL' },
  { city: 'Hoover',        stateCode: 'AL' },
  { city: 'Auburn',        stateCode: 'AL' },
  { city: 'Dothan',        stateCode: 'AL' },
  { city: 'Decatur',       stateCode: 'AL' },
  { city: 'Madison',       stateCode: 'AL' },
  { city: 'Phenix City',   stateCode: 'AL' },
  { city: 'Florence',      stateCode: 'AL' },

  // Alaska
  { city: 'Anchorage',     stateCode: 'AK' },
  { city: 'Fairbanks',     stateCode: 'AK' },
  { city: 'Juneau',        stateCode: 'AK' },
  { city: 'Sitka',         stateCode: 'AK' },
  { city: 'Ketchikan',     stateCode: 'AK' },
  { city: 'Wasilla',       stateCode: 'AK' },
  { city: 'Kenai',         stateCode: 'AK' },
  { city: 'Kodiak',        stateCode: 'AK' },

  // Arizona
  { city: 'Phoenix',       stateCode: 'AZ' },
  { city: 'Tucson',        stateCode: 'AZ' },
  { city: 'Mesa',          stateCode: 'AZ' },
  { city: 'Chandler',      stateCode: 'AZ' },
  { city: 'Scottsdale',    stateCode: 'AZ' },
  { city: 'Glendale',      stateCode: 'AZ' },
  { city: 'Gilbert',       stateCode: 'AZ' },
  { city: 'Tempe',         stateCode: 'AZ' },
  { city: 'Peoria',        stateCode: 'AZ' },
  { city: 'Flagstaff',     stateCode: 'AZ' },
  { city: 'Surprise',      stateCode: 'AZ' },
  { city: 'Yuma',          stateCode: 'AZ' },
  { city: 'Avondale',      stateCode: 'AZ' },

  // Arkansas
  { city: 'Little Rock',   stateCode: 'AR' },
  { city: 'Fort Smith',    stateCode: 'AR' },
  { city: 'Fayetteville',  stateCode: 'AR' },
  { city: 'Springdale',    stateCode: 'AR' },
  { city: 'Jonesboro',     stateCode: 'AR' },
  { city: 'Rogers',        stateCode: 'AR' },
  { city: 'Bentonville',   stateCode: 'AR' },
  { city: 'Pine Bluff',    stateCode: 'AR' },
  { city: 'Conway',        stateCode: 'AR' },
  { city: 'North Little Rock', stateCode: 'AR' },

  // California
  { city: 'Los Angeles',   stateCode: 'CA' },
  { city: 'San Diego',     stateCode: 'CA' },
  { city: 'San Jose',      stateCode: 'CA' },
  { city: 'San Francisco', stateCode: 'CA' },
  { city: 'Fresno',        stateCode: 'CA' },
  { city: 'Sacramento',    stateCode: 'CA' },
  { city: 'Long Beach',    stateCode: 'CA' },
  { city: 'Oakland',       stateCode: 'CA' },
  { city: 'Bakersfield',   stateCode: 'CA' },
  { city: 'Anaheim',       stateCode: 'CA' },
  { city: 'Santa Ana',     stateCode: 'CA' },
  { city: 'Riverside',     stateCode: 'CA' },
  { city: 'Irvine',        stateCode: 'CA' },
  { city: 'San Bernardino', stateCode: 'CA' },
  { city: 'Torrance',      stateCode: 'CA' },

  // Colorado
  { city: 'Denver',        stateCode: 'CO' },
  { city: 'Colorado Springs', stateCode: 'CO' },
  { city: 'Aurora',        stateCode: 'CO' },
  { city: 'Fort Collins',  stateCode: 'CO' },
  { city: 'Lakewood',      stateCode: 'CO' },
  { city: 'Thornton',      stateCode: 'CO' },
  { city: 'Arvada',        stateCode: 'CO' },
  { city: 'Westminster',   stateCode: 'CO' },
  { city: 'Pueblo',        stateCode: 'CO' },
  { city: 'Boulder',       stateCode: 'CO' },
  { city: 'Greeley',       stateCode: 'CO' },

  // Connecticut
  { city: 'Bridgeport',    stateCode: 'CT' },
  { city: 'New Haven',     stateCode: 'CT' },
  { city: 'Hartford',      stateCode: 'CT' },
  { city: 'Stamford',      stateCode: 'CT' },
  { city: 'Waterbury',     stateCode: 'CT' },
  { city: 'Norwalk',       stateCode: 'CT' },
  { city: 'Danbury',       stateCode: 'CT' },
  { city: 'New Britain',   stateCode: 'CT' },
  { city: 'West Hartford', stateCode: 'CT' },
  { city: 'Greenwich',     stateCode: 'CT' },

  // Delaware
  { city: 'Wilmington',    stateCode: 'DE' },
  { city: 'Dover',         stateCode: 'DE' },
  { city: 'Newark',        stateCode: 'DE' },
  { city: 'Middletown',    stateCode: 'DE' },
  { city: 'Smyrna',        stateCode: 'DE' },
  { city: 'Milford',       stateCode: 'DE' },

  // Florida
  { city: 'Jacksonville',  stateCode: 'FL' },
  { city: 'Miami',         stateCode: 'FL' },
  { city: 'Tampa',         stateCode: 'FL' },
  { city: 'Orlando',       stateCode: 'FL' },
  { city: 'St. Petersburg', stateCode: 'FL' },
  { city: 'Hialeah',       stateCode: 'FL' },
  { city: 'Tallahassee',   stateCode: 'FL' },
  { city: 'Fort Lauderdale', stateCode: 'FL' },
  { city: 'Port St. Lucie', stateCode: 'FL' },
  { city: 'Pembroke Pines', stateCode: 'FL' },
  { city: 'Gainesville',   stateCode: 'FL' },
  { city: 'Clearwater',    stateCode: 'FL' },
  { city: 'Boca Raton',    stateCode: 'FL' },

  // Georgia
  { city: 'Atlanta',       stateCode: 'GA' },
  { city: 'Columbus',      stateCode: 'GA' },
  { city: 'Augusta',       stateCode: 'GA' },
  { city: 'Savannah',      stateCode: 'GA' },
  { city: 'Macon',         stateCode: 'GA' },
  { city: 'Roswell',       stateCode: 'GA' },
  { city: 'Albany',        stateCode: 'GA' },
  { city: 'Johns Creek',   stateCode: 'GA' },
  { city: 'Warner Robins', stateCode: 'GA' },
  { city: 'Athens',        stateCode: 'GA' },
  { city: 'Sandy Springs', stateCode: 'GA' },
  { city: 'Marietta',      stateCode: 'GA' },

  // Hawaii
  { city: 'Honolulu',      stateCode: 'HI' },
  { city: 'Pearl City',    stateCode: 'HI' },
  { city: 'Hilo',          stateCode: 'HI' },
  { city: 'Kailua',        stateCode: 'HI' },
  { city: 'Waipahu',       stateCode: 'HI' },
  { city: 'Kaneohe',       stateCode: 'HI' },
  { city: 'Mililani',      stateCode: 'HI' },
  { city: 'Kahului',       stateCode: 'HI' },
  { city: 'Kihei',         stateCode: 'HI' },

  // Idaho
  { city: 'Boise',         stateCode: 'ID' },
  { city: 'Nampa',         stateCode: 'ID' },
  { city: 'Meridian',      stateCode: 'ID' },
  { city: 'Idaho Falls',   stateCode: 'ID' },
  { city: 'Pocatello',     stateCode: 'ID' },
  { city: 'Caldwell',      stateCode: 'ID' },
  { city: 'Coeur d\'Alene', stateCode: 'ID' },
  { city: 'Twin Falls',    stateCode: 'ID' },
  { city: 'Lewiston',      stateCode: 'ID' },

  // Illinois
  { city: 'Chicago',       stateCode: 'IL' },
  { city: 'Aurora',        stateCode: 'IL' },
  { city: 'Joliet',        stateCode: 'IL' },
  { city: 'Naperville',    stateCode: 'IL' },
  { city: 'Rockford',      stateCode: 'IL' },
  { city: 'Springfield',   stateCode: 'IL' },
  { city: 'Elgin',         stateCode: 'IL' },
  { city: 'Peoria',        stateCode: 'IL' },
  { city: 'Champaign',     stateCode: 'IL' },
  { city: 'Waukegan',      stateCode: 'IL' },
  { city: 'Cicero',        stateCode: 'IL' },
  { city: 'Evanston',      stateCode: 'IL' },

  // Indiana
  { city: 'Indianapolis',  stateCode: 'IN' },
  { city: 'Fort Wayne',    stateCode: 'IN' },
  { city: 'Evansville',    stateCode: 'IN' },
  { city: 'South Bend',    stateCode: 'IN' },
  { city: 'Carmel',        stateCode: 'IN' },
  { city: 'Fishers',       stateCode: 'IN' },
  { city: 'Bloomington',   stateCode: 'IN' },
  { city: 'Hammond',       stateCode: 'IN' },
  { city: 'Gary',          stateCode: 'IN' },
  { city: 'Lafayette',     stateCode: 'IN' },
  { city: 'Muncie',        stateCode: 'IN' },

  // Iowa
  { city: 'Des Moines',    stateCode: 'IA' },
  { city: 'Cedar Rapids',  stateCode: 'IA' },
  { city: 'Davenport',     stateCode: 'IA' },
  { city: 'Sioux City',    stateCode: 'IA' },
  { city: 'Iowa City',     stateCode: 'IA' },
  { city: 'Waterloo',      stateCode: 'IA' },
  { city: 'Ames',          stateCode: 'IA' },
  { city: 'Ankeny',        stateCode: 'IA' },
  { city: 'Dubuque',       stateCode: 'IA' },
  { city: 'Council Bluffs', stateCode: 'IA' },

  // Kansas
  { city: 'Wichita',       stateCode: 'KS' },
  { city: 'Overland Park', stateCode: 'KS' },
  { city: 'Kansas City',   stateCode: 'KS' },
  { city: 'Topeka',        stateCode: 'KS' },
  { city: 'Olathe',        stateCode: 'KS' },
  { city: 'Lawrence',      stateCode: 'KS' },
  { city: 'Shawnee',       stateCode: 'KS' },
  { city: 'Manhattan',     stateCode: 'KS' },
  { city: 'Lenexa',        stateCode: 'KS' },
  { city: 'Salina',        stateCode: 'KS' },

  // Kentucky
  { city: 'Louisville',    stateCode: 'KY' },
  { city: 'Lexington',     stateCode: 'KY' },
  { city: 'Bowling Green', stateCode: 'KY' },
  { city: 'Owensboro',     stateCode: 'KY' },
  { city: 'Covington',     stateCode: 'KY' },
  { city: 'Frankfort',     stateCode: 'KY' },
  { city: 'Georgetown',    stateCode: 'KY' },
  { city: 'Florence',      stateCode: 'KY' },
  { city: 'Hopkinsville',  stateCode: 'KY' },
  { city: 'Richmond',      stateCode: 'KY' },

  // Louisiana
  { city: 'New Orleans',   stateCode: 'LA' },
  { city: 'Baton Rouge',   stateCode: 'LA' },
  { city: 'Shreveport',    stateCode: 'LA' },
  { city: 'Lafayette',     stateCode: 'LA' },
  { city: 'Lake Charles',  stateCode: 'LA' },
  { city: 'Kenner',        stateCode: 'LA' },
  { city: 'Bossier City',  stateCode: 'LA' },
  { city: 'Monroe',        stateCode: 'LA' },
  { city: 'Alexandria',    stateCode: 'LA' },
  { city: 'Metairie',      stateCode: 'LA' },

  // Maine
  { city: 'Portland',      stateCode: 'ME' },
  { city: 'Lewiston',      stateCode: 'ME' },
  { city: 'Bangor',        stateCode: 'ME' },
  { city: 'South Portland', stateCode: 'ME' },
  { city: 'Augusta',       stateCode: 'ME' },
  { city: 'Biddeford',     stateCode: 'ME' },
  { city: 'Sanford',       stateCode: 'ME' },
  { city: 'Brunswick',     stateCode: 'ME' },

  // Maryland
  { city: 'Baltimore',     stateCode: 'MD' },
  { city: 'Frederick',     stateCode: 'MD' },
  { city: 'Rockville',     stateCode: 'MD' },
  { city: 'Gaithersburg',  stateCode: 'MD' },
  { city: 'Bowie',         stateCode: 'MD' },
  { city: 'Hagerstown',    stateCode: 'MD' },
  { city: 'Annapolis',     stateCode: 'MD' },
  { city: 'College Park',  stateCode: 'MD' },
  { city: 'Germantown',    stateCode: 'MD' },
  { city: 'Salisbury',     stateCode: 'MD' },
  { city: 'Silver Spring', stateCode: 'MD' },

  // Massachusetts
  { city: 'Boston',        stateCode: 'MA' },
  { city: 'Worcester',     stateCode: 'MA' },
  { city: 'Springfield',   stateCode: 'MA' },
  { city: 'Cambridge',     stateCode: 'MA' },
  { city: 'Lowell',        stateCode: 'MA' },
  { city: 'Brockton',      stateCode: 'MA' },
  { city: 'New Bedford',   stateCode: 'MA' },
  { city: 'Quincy',        stateCode: 'MA' },
  { city: 'Lynn',          stateCode: 'MA' },
  { city: 'Fall River',    stateCode: 'MA' },
  { city: 'Somerville',    stateCode: 'MA' },
  { city: 'Medford',       stateCode: 'MA' },

  // Michigan
  { city: 'Detroit',       stateCode: 'MI' },
  { city: 'Grand Rapids',  stateCode: 'MI' },
  { city: 'Warren',        stateCode: 'MI' },
  { city: 'Sterling Heights', stateCode: 'MI' },
  { city: 'Ann Arbor',     stateCode: 'MI' },
  { city: 'Lansing',       stateCode: 'MI' },
  { city: 'Flint',         stateCode: 'MI' },
  { city: 'Dearborn',      stateCode: 'MI' },
  { city: 'Livonia',       stateCode: 'MI' },
  { city: 'Westland',      stateCode: 'MI' },
  { city: 'Kalamazoo',     stateCode: 'MI' },
  { city: 'Troy',          stateCode: 'MI' },
  { city: 'Pontiac',       stateCode: 'MI' },

  // Minnesota
  { city: 'Minneapolis',   stateCode: 'MN' },
  { city: 'Saint Paul',    stateCode: 'MN' },
  { city: 'Rochester',     stateCode: 'MN' },
  { city: 'Duluth',        stateCode: 'MN' },
  { city: 'Bloomington',   stateCode: 'MN' },
  { city: 'Plymouth',      stateCode: 'MN' },
  { city: 'Brooklyn Park', stateCode: 'MN' },
  { city: 'Maple Grove',   stateCode: 'MN' },
  { city: 'Woodbury',      stateCode: 'MN' },
  { city: 'Eagan',         stateCode: 'MN' },
  { city: 'Burnsville',    stateCode: 'MN' },

  // Mississippi
  { city: 'Jackson',       stateCode: 'MS' },
  { city: 'Gulfport',      stateCode: 'MS' },
  { city: 'Southaven',     stateCode: 'MS' },
  { city: 'Hattiesburg',   stateCode: 'MS' },
  { city: 'Biloxi',        stateCode: 'MS' },
  { city: 'Meridian',      stateCode: 'MS' },
  { city: 'Tupelo',        stateCode: 'MS' },
  { city: 'Olive Branch',  stateCode: 'MS' },
  { city: 'Starkville',    stateCode: 'MS' },
  { city: 'Oxford',        stateCode: 'MS' },

  // Missouri
  { city: 'Kansas City',   stateCode: 'MO' },
  { city: 'St. Louis',     stateCode: 'MO' },
  { city: 'Springfield',   stateCode: 'MO' },
  { city: 'Columbia',      stateCode: 'MO' },
  { city: 'Independence',  stateCode: 'MO' },
  { city: 'Lee\'s Summit', stateCode: 'MO' },
  { city: 'O\'Fallon',     stateCode: 'MO' },
  { city: 'St. Joseph',    stateCode: 'MO' },
  { city: 'St. Charles',   stateCode: 'MO' },
  { city: 'Jefferson City', stateCode: 'MO' },
  { city: 'Joplin',        stateCode: 'MO' },

  // Montana
  { city: 'Billings',      stateCode: 'MT' },
  { city: 'Missoula',      stateCode: 'MT' },
  { city: 'Great Falls',   stateCode: 'MT' },
  { city: 'Bozeman',       stateCode: 'MT' },
  { city: 'Butte',         stateCode: 'MT' },
  { city: 'Helena',        stateCode: 'MT' },
  { city: 'Kalispell',     stateCode: 'MT' },
  { city: 'Havre',         stateCode: 'MT' },

  // Nebraska
  { city: 'Omaha',         stateCode: 'NE' },
  { city: 'Lincoln',       stateCode: 'NE' },
  { city: 'Bellevue',      stateCode: 'NE' },
  { city: 'Grand Island',  stateCode: 'NE' },
  { city: 'Kearney',       stateCode: 'NE' },
  { city: 'Fremont',       stateCode: 'NE' },
  { city: 'Hastings',      stateCode: 'NE' },
  { city: 'Norfolk',       stateCode: 'NE' },
  { city: 'Columbus',      stateCode: 'NE' },

  // Nevada
  { city: 'Las Vegas',     stateCode: 'NV' },
  { city: 'Henderson',     stateCode: 'NV' },
  { city: 'Reno',          stateCode: 'NV' },
  { city: 'North Las Vegas', stateCode: 'NV' },
  { city: 'Sparks',        stateCode: 'NV' },
  { city: 'Carson City',   stateCode: 'NV' },
  { city: 'Sunrise Manor', stateCode: 'NV' },
  { city: 'Spring Valley', stateCode: 'NV' },
  { city: 'Enterprise',    stateCode: 'NV' },
  { city: 'Summerlin',     stateCode: 'NV' },

  // New Hampshire
  { city: 'Manchester',    stateCode: 'NH' },
  { city: 'Nashua',        stateCode: 'NH' },
  { city: 'Concord',       stateCode: 'NH' },
  { city: 'Derry',         stateCode: 'NH' },
  { city: 'Rochester',     stateCode: 'NH' },
  { city: 'Dover',         stateCode: 'NH' },
  { city: 'Salem',         stateCode: 'NH' },
  { city: 'Merrimack',     stateCode: 'NH' },
  { city: 'Portsmouth',    stateCode: 'NH' },

  // New Jersey
  { city: 'Newark',        stateCode: 'NJ' },
  { city: 'Jersey City',   stateCode: 'NJ' },
  { city: 'Paterson',      stateCode: 'NJ' },
  { city: 'Elizabeth',     stateCode: 'NJ' },
  { city: 'Edison',        stateCode: 'NJ' },
  { city: 'Woodbridge',    stateCode: 'NJ' },
  { city: 'Lakewood',      stateCode: 'NJ' },
  { city: 'Toms River',    stateCode: 'NJ' },
  { city: 'Trenton',       stateCode: 'NJ' },
  { city: 'Hamilton',      stateCode: 'NJ' },
  { city: 'Clifton',       stateCode: 'NJ' },
  { city: 'Camden',        stateCode: 'NJ' },

  // New Mexico
  { city: 'Albuquerque',   stateCode: 'NM' },
  { city: 'Las Cruces',    stateCode: 'NM' },
  { city: 'Rio Rancho',    stateCode: 'NM' },
  { city: 'Santa Fe',      stateCode: 'NM' },
  { city: 'Roswell',       stateCode: 'NM' },
  { city: 'Farmington',    stateCode: 'NM' },
  { city: 'Clovis',        stateCode: 'NM' },
  { city: 'Hobbs',         stateCode: 'NM' },
  { city: 'Alamogordo',    stateCode: 'NM' },

  // New York
  { city: 'New York City', stateCode: 'NY' },
  { city: 'Buffalo',       stateCode: 'NY' },
  { city: 'Rochester',     stateCode: 'NY' },
  { city: 'Yonkers',       stateCode: 'NY' },
  { city: 'Syracuse',      stateCode: 'NY' },
  { city: 'Albany',        stateCode: 'NY' },
  { city: 'New Rochelle',  stateCode: 'NY' },
  { city: 'Mount Vernon',  stateCode: 'NY' },
  { city: 'Schenectady',   stateCode: 'NY' },
  { city: 'Utica',         stateCode: 'NY' },
  { city: 'White Plains',  stateCode: 'NY' },
  { city: 'Flushing',      stateCode: 'NY' },
  { city: 'Brooklyn',      stateCode: 'NY' },

  // North Carolina
  { city: 'Charlotte',     stateCode: 'NC' },
  { city: 'Raleigh',       stateCode: 'NC' },
  { city: 'Greensboro',    stateCode: 'NC' },
  { city: 'Durham',        stateCode: 'NC' },
  { city: 'Winston-Salem', stateCode: 'NC' },
  { city: 'Fayetteville',  stateCode: 'NC' },
  { city: 'Cary',          stateCode: 'NC' },
  { city: 'Wilmington',    stateCode: 'NC' },
  { city: 'High Point',    stateCode: 'NC' },
  { city: 'Concord',       stateCode: 'NC' },
  { city: 'Asheville',     stateCode: 'NC' },
  { city: 'Chapel Hill',   stateCode: 'NC' },

  // North Dakota
  { city: 'Fargo',         stateCode: 'ND' },
  { city: 'Bismarck',      stateCode: 'ND' },
  { city: 'Grand Forks',   stateCode: 'ND' },
  { city: 'Minot',         stateCode: 'ND' },
  { city: 'West Fargo',    stateCode: 'ND' },
  { city: 'Mandan',        stateCode: 'ND' },
  { city: 'Dickinson',     stateCode: 'ND' },
  { city: 'Jamestown',     stateCode: 'ND' },

  // Ohio
  { city: 'Columbus',      stateCode: 'OH' },
  { city: 'Cleveland',     stateCode: 'OH' },
  { city: 'Cincinnati',    stateCode: 'OH' },
  { city: 'Toledo',        stateCode: 'OH' },
  { city: 'Akron',         stateCode: 'OH' },
  { city: 'Dayton',        stateCode: 'OH' },
  { city: 'Parma',         stateCode: 'OH' },
  { city: 'Canton',        stateCode: 'OH' },
  { city: 'Youngstown',    stateCode: 'OH' },
  { city: 'Lorain',        stateCode: 'OH' },
  { city: 'Hamilton',      stateCode: 'OH' },
  { city: 'Kettering',     stateCode: 'OH' },

  // Oklahoma
  { city: 'Oklahoma City', stateCode: 'OK' },
  { city: 'Tulsa',         stateCode: 'OK' },
  { city: 'Norman',        stateCode: 'OK' },
  { city: 'Broken Arrow',  stateCode: 'OK' },
  { city: 'Lawton',        stateCode: 'OK' },
  { city: 'Edmond',        stateCode: 'OK' },
  { city: 'Moore',         stateCode: 'OK' },
  { city: 'Midwest City',  stateCode: 'OK' },
  { city: 'Enid',          stateCode: 'OK' },
  { city: 'Stillwater',    stateCode: 'OK' },

  // Oregon
  { city: 'Portland',      stateCode: 'OR' },
  { city: 'Salem',         stateCode: 'OR' },
  { city: 'Eugene',        stateCode: 'OR' },
  { city: 'Gresham',       stateCode: 'OR' },
  { city: 'Hillsboro',     stateCode: 'OR' },
  { city: 'Beaverton',     stateCode: 'OR' },
  { city: 'Bend',          stateCode: 'OR' },
  { city: 'Medford',       stateCode: 'OR' },
  { city: 'Springfield',   stateCode: 'OR' },
  { city: 'Corvallis',     stateCode: 'OR' },
  { city: 'Albany',        stateCode: 'OR' },

  // Pennsylvania
  { city: 'Philadelphia',  stateCode: 'PA' },
  { city: 'Pittsburgh',    stateCode: 'PA' },
  { city: 'Allentown',     stateCode: 'PA' },
  { city: 'Erie',          stateCode: 'PA' },
  { city: 'Reading',       stateCode: 'PA' },
  { city: 'Scranton',      stateCode: 'PA' },
  { city: 'Bethlehem',     stateCode: 'PA' },
  { city: 'Lancaster',     stateCode: 'PA' },
  { city: 'Harrisburg',    stateCode: 'PA' },
  { city: 'York',          stateCode: 'PA' },
  { city: 'State College', stateCode: 'PA' },
  { city: 'Wilkes-Barre',  stateCode: 'PA' },

  // Rhode Island
  { city: 'Providence',    stateCode: 'RI' },
  { city: 'Cranston',      stateCode: 'RI' },
  { city: 'Warwick',       stateCode: 'RI' },
  { city: 'Pawtucket',     stateCode: 'RI' },
  { city: 'East Providence', stateCode: 'RI' },
  { city: 'Woonsocket',    stateCode: 'RI' },
  { city: 'Newport',       stateCode: 'RI' },

  // South Carolina
  { city: 'Columbia',      stateCode: 'SC' },
  { city: 'Charleston',    stateCode: 'SC' },
  { city: 'North Charleston', stateCode: 'SC' },
  { city: 'Mount Pleasant', stateCode: 'SC' },
  { city: 'Rock Hill',     stateCode: 'SC' },
  { city: 'Greenville',    stateCode: 'SC' },
  { city: 'Summerville',   stateCode: 'SC' },
  { city: 'Sumter',        stateCode: 'SC' },
  { city: 'Hilton Head Island', stateCode: 'SC' },
  { city: 'Florence',      stateCode: 'SC' },
  { city: 'Spartanburg',   stateCode: 'SC' },

  // South Dakota
  { city: 'Sioux Falls',   stateCode: 'SD' },
  { city: 'Rapid City',    stateCode: 'SD' },
  { city: 'Aberdeen',      stateCode: 'SD' },
  { city: 'Brookings',     stateCode: 'SD' },
  { city: 'Watertown',     stateCode: 'SD' },
  { city: 'Mitchell',      stateCode: 'SD' },
  { city: 'Pierre',        stateCode: 'SD' },

  // Tennessee
  { city: 'Nashville',     stateCode: 'TN' },
  { city: 'Memphis',       stateCode: 'TN' },
  { city: 'Knoxville',     stateCode: 'TN' },
  { city: 'Chattanooga',   stateCode: 'TN' },
  { city: 'Clarksville',   stateCode: 'TN' },
  { city: 'Murfreesboro',  stateCode: 'TN' },
  { city: 'Franklin',      stateCode: 'TN' },
  { city: 'Jackson',       stateCode: 'TN' },
  { city: 'Johnson City',  stateCode: 'TN' },
  { city: 'Bartlett',      stateCode: 'TN' },
  { city: 'Brentwood',     stateCode: 'TN' },

  // Texas
  { city: 'Houston',       stateCode: 'TX' },
  { city: 'San Antonio',   stateCode: 'TX' },
  { city: 'Dallas',        stateCode: 'TX' },
  { city: 'Austin',        stateCode: 'TX' },
  { city: 'Fort Worth',    stateCode: 'TX' },
  { city: 'El Paso',       stateCode: 'TX' },
  { city: 'Arlington',     stateCode: 'TX' },
  { city: 'Corpus Christi', stateCode: 'TX' },
  { city: 'Plano',         stateCode: 'TX' },
  { city: 'Laredo',        stateCode: 'TX' },
  { city: 'Lubbock',       stateCode: 'TX' },
  { city: 'Irving',        stateCode: 'TX' },
  { city: 'Garland',       stateCode: 'TX' },
  { city: 'Frisco',        stateCode: 'TX' },
  { city: 'McKinney',      stateCode: 'TX' },

  // Utah
  { city: 'Salt Lake City', stateCode: 'UT' },
  { city: 'West Valley City', stateCode: 'UT' },
  { city: 'Provo',         stateCode: 'UT' },
  { city: 'West Jordan',   stateCode: 'UT' },
  { city: 'Orem',          stateCode: 'UT' },
  { city: 'Sandy',         stateCode: 'UT' },
  { city: 'Ogden',         stateCode: 'UT' },
  { city: 'St. George',    stateCode: 'UT' },
  { city: 'Layton',        stateCode: 'UT' },
  { city: 'Taylorsville',  stateCode: 'UT' },

  // Vermont
  { city: 'Burlington',    stateCode: 'VT' },
  { city: 'South Burlington', stateCode: 'VT' },
  { city: 'Rutland',       stateCode: 'VT' },
  { city: 'Barre',         stateCode: 'VT' },
  { city: 'Montpelier',    stateCode: 'VT' },
  { city: 'Winooski',      stateCode: 'VT' },
  { city: 'St. Johnsbury', stateCode: 'VT' },

  // Virginia
  { city: 'Virginia Beach', stateCode: 'VA' },
  { city: 'Norfolk',       stateCode: 'VA' },
  { city: 'Chesapeake',    stateCode: 'VA' },
  { city: 'Richmond',      stateCode: 'VA' },
  { city: 'Newport News',  stateCode: 'VA' },
  { city: 'Alexandria',    stateCode: 'VA' },
  { city: 'Hampton',       stateCode: 'VA' },
  { city: 'Roanoke',       stateCode: 'VA' },
  { city: 'Portsmouth',    stateCode: 'VA' },
  { city: 'Suffolk',       stateCode: 'VA' },
  { city: 'Lynchburg',     stateCode: 'VA' },
  { city: 'Charlottesville', stateCode: 'VA' },

  // Washington
  { city: 'Seattle',       stateCode: 'WA' },
  { city: 'Spokane',       stateCode: 'WA' },
  { city: 'Tacoma',        stateCode: 'WA' },
  { city: 'Vancouver',     stateCode: 'WA' },
  { city: 'Bellevue',      stateCode: 'WA' },
  { city: 'Kent',          stateCode: 'WA' },
  { city: 'Everett',       stateCode: 'WA' },
  { city: 'Renton',        stateCode: 'WA' },
  { city: 'Spokane Valley', stateCode: 'WA' },
  { city: 'Federal Way',   stateCode: 'WA' },
  { city: 'Bellingham',    stateCode: 'WA' },
  { city: 'Kirkland',      stateCode: 'WA' },
  { city: 'Redmond',       stateCode: 'WA' },

  // West Virginia
  { city: 'Charleston',    stateCode: 'WV' },
  { city: 'Huntington',    stateCode: 'WV' },
  { city: 'Parkersburg',   stateCode: 'WV' },
  { city: 'Morgantown',    stateCode: 'WV' },
  { city: 'Wheeling',      stateCode: 'WV' },
  { city: 'Weirton',       stateCode: 'WV' },
  { city: 'Fairmont',      stateCode: 'WV' },
  { city: 'Beckley',       stateCode: 'WV' },

  // Wisconsin
  { city: 'Milwaukee',     stateCode: 'WI' },
  { city: 'Madison',       stateCode: 'WI' },
  { city: 'Green Bay',     stateCode: 'WI' },
  { city: 'Kenosha',       stateCode: 'WI' },
  { city: 'Racine',        stateCode: 'WI' },
  { city: 'Appleton',      stateCode: 'WI' },
  { city: 'Waukesha',      stateCode: 'WI' },
  { city: 'Oshkosh',       stateCode: 'WI' },
  { city: 'Eau Claire',    stateCode: 'WI' },
  { city: 'Janesville',    stateCode: 'WI' },
  { city: 'La Crosse',     stateCode: 'WI' },

  // Wyoming
  { city: 'Cheyenne',      stateCode: 'WY' },
  { city: 'Casper',        stateCode: 'WY' },
  { city: 'Laramie',       stateCode: 'WY' },
  { city: 'Gillette',      stateCode: 'WY' },
  { city: 'Rock Springs',  stateCode: 'WY' },
  { city: 'Sheridan',      stateCode: 'WY' },
  { city: 'Green River',   stateCode: 'WY' },
]

/** All major city params, e.g. "chicago-il", "houston-tx" */
export const MAJOR_CITIES_PARAMS: string[] = MAJOR_CITIES.map(
  c => `${slugify(c.city)}-${c.stateCode.toLowerCase()}`
)
