import { pickStockPhoto } from './stock-photos'

export interface RecipeIngredient {
  amount: string  // e.g. "1" — scaled/converted client-side against baseServings
  unit: string     // e.g. "tablespoon", "cup" — shown as-is, pluralized client-side
  metricAmount?: string // e.g. "15" for the Metric unit toggle
  metricUnit?: string   // e.g. "ml"
  item: string     // e.g. "sesame oil"
  note?: string     // e.g. "I used chicken, but vegetable would also work"
}

export interface RecipeStep {
  text: string
}

export interface NutritionFacts {
  calories: number
  protein: string
  carbs: string
  fat: string
  fiber: string
  sugar: string
  sodium: string
}

export interface Recipe {
  slug: string
  title: string           // page H1 / title tag
  cardTitle: string        // shorter title shown on the printable card
  description: string
  image: string
  gallery?: string[]       // optional extra photos shown on the recipe page
  rating: number
  reviewCount: number
  prepTime: string
  cookTime: string
  totalTime: string
  baseServings: number
  servingsLabel: string    // e.g. "heaping 1-cup servings"
  ingredients: RecipeIngredient[]
  steps: RecipeStep[]
  whatToAdd: { title: string; text: string }[]
  nutrition: NutritionFacts
  category: string
  date: string
}

export const RECIPES: Recipe[] = [
  {
    slug: 'quick-homemade-ramen',
    title: 'Quick Homemade Ramen Recipe',
    cardTitle: 'Quick Homemade Ramen',
    description:
      "Take instant ramen up a notch — or skip it entirely. This quick homemade ramen builds a genuinely savory broth from pantry staples in about 25 minutes, then lets you load it up with whatever fresh veggies, herbs, and toppings you have on hand. It's the easy weeknight version of a bowl that usually takes all day.",
    image: pickStockPhoto('quick-homemade-ramen'),
    rating: 4.4,
    reviewCount: 118,
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    totalTime: '25 minutes',
    baseServings: 4,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'sesame oil' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'grated ginger' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'grated garlic' },
      { amount: '4', unit: 'cups', metricAmount: '950', metricUnit: 'ml', item: 'broth', note: 'chicken, vegetable, or dashi all work' },
      { amount: '2', unit: 'cups', metricAmount: '475', metricUnit: 'ml', item: 'water' },
      { amount: '3', unit: 'tablespoons', metricAmount: '45', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'mirin' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'g', item: 'white miso paste' },
      { amount: '8', unit: 'ounces', metricAmount: '225', metricUnit: 'g', item: 'ramen noodles', note: 'fresh or dried; instant noodle bricks work in a pinch' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'soft-boiled eggs, halved' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'scallions, thinly sliced' },
      { amount: '1', unit: 'sheet', metricAmount: '1', metricUnit: 'sheet', item: 'nori, cut into strips' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'ml', item: 'chili oil', note: 'optional, for heat' },
    ],
    steps: [
      { text: 'Warm the sesame oil in a pot over medium heat. Add the grated ginger and garlic and sauté for about 90 seconds, until fragrant — don\'t let the garlic brown.' },
      { text: 'Pour in the broth and water. Bring to a gentle simmer.' },
      { text: 'Stir in the soy sauce and mirin. Whisk the miso paste with a splash of the hot broth in a small bowl until smooth, then stir it back into the pot — this keeps the miso from clumping.' },
      { text: 'Let the broth simmer for 10 minutes so the flavors come together, tasting and adjusting the soy sauce or miso as needed.' },
      { text: 'While the broth simmers, cook the ramen noodles separately according to the package instructions, then drain.' },
      { text: 'Warm your serving bowls with hot water for a minute, then dump it out — a warm bowl keeps the ramen hotter longer.' },
      { text: 'Divide the noodles among the bowls, ladle the hot broth over top, and arrange the egg, scallions, and nori neatly on top. Finish with chili oil if using, and serve immediately.' },
    ],
    whatToAdd: [
      { title: 'Protein', text: 'Sliced chashu pork, leftover rotisserie chicken, seared tofu, or shrimp all work well simmered briefly in the broth or added just before serving.' },
      { title: 'Vegetables', text: 'Baby bok choy, corn, bean sprouts, mushrooms, and spinach are classic additions — add heartier vegetables to the simmering broth in the last few minutes so they soften.' },
      { title: 'More heat', text: 'A spoonful of gochujang or extra chili oil turns this into a spicy miso-style bowl.' },
      { title: 'Richness', text: 'A pat of butter or a drizzle of chili crisp stirred in right before serving adds the kind of richness you\'d get from a longer-simmered broth.' },
    ],
    nutrition: {
      calories: 420,
      protein: '18g',
      carbs: '52g',
      fat: '14g',
      fiber: '3g',
      sugar: '4g',
      sodium: '1450mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'homemade-chicken-ramen',
    title: 'Homemade Chicken Ramen Recipe',
    cardTitle: 'Homemade Chicken Ramen',
    description:
      "This homemade chicken ramen builds a deeply savory, golden broth by simmering bone-in chicken thighs right in the pot — no separate stock-making required. Shredded chicken, a soft-boiled egg, and a tangle of noodles make this a complete, comforting bowl in under an hour.",
    image: pickStockPhoto('homemade-chicken-ramen'),
    rating: 4.6,
    reviewCount: 94,
    prepTime: '10 minutes',
    cookTime: '40 minutes',
    totalTime: '50 minutes',
    baseServings: 4,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'vegetable oil' },
      { amount: '1.5', unit: 'lbs', metricAmount: '680', metricUnit: 'g', item: 'bone-in, skin-on chicken thighs' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'grated ginger' },
      { amount: '3', unit: 'cloves', metricAmount: '3', metricUnit: 'cloves', item: 'garlic, smashed' },
      { amount: '6', unit: 'cups', metricAmount: '1420', metricUnit: 'ml', item: 'chicken stock' },
      { amount: '3', unit: 'tablespoons', metricAmount: '45', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'mirin' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'ml', item: 'rice vinegar' },
      { amount: '8', unit: 'ounces', metricAmount: '225', metricUnit: 'g', item: 'ramen noodles' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'soft-boiled eggs, halved' },
      { amount: '1', unit: 'cup', metricAmount: '150', metricUnit: 'g', item: 'corn kernels' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'scallions, thinly sliced' },
    ],
    steps: [
      { text: 'Heat the oil in a large pot over medium-high heat. Season the chicken thighs with salt and sear skin-side down for 4–5 minutes, until golden. Flip and sear another 2 minutes.' },
      { text: 'Add the ginger and garlic and sauté for 30 seconds, until fragrant.' },
      { text: 'Pour in the chicken stock, scraping up any browned bits from the bottom of the pot. Bring to a boil, then reduce to a simmer.' },
      { text: 'Cover and simmer for 30 minutes, until the chicken is cooked through and easily shreds with a fork.' },
      { text: 'Remove the chicken, shred the meat off the bone, and discard the skin and bones. Set the shredded chicken aside.' },
      { text: 'Stir the soy sauce, mirin, and rice vinegar into the broth. Taste and adjust seasoning.' },
      { text: 'Cook the ramen noodles separately according to the package instructions, then drain.' },
      { text: 'Divide the noodles among bowls, ladle the hot broth over top, and top with the shredded chicken, egg, corn, and scallions.' },
    ],
    whatToAdd: [
      { title: 'Extra umami', text: 'A spoonful of miso paste whisked into the broth adds depth without changing the chicken-forward flavor.' },
      { title: 'Vegetables', text: 'Baby bok choy, mushrooms, and bean sprouts all simmer well in the last few minutes of cooking.' },
      { title: 'Heat', text: 'Chili oil or a spoonful of chili crisp on top brings a spicy contrast to the mild broth.' },
      { title: 'Crunch', text: 'Toasted sesame seeds or crispy fried shallots add texture right before serving.' },
    ],
    nutrition: {
      calories: 480,
      protein: '32g',
      carbs: '48g',
      fat: '17g',
      fiber: '2g',
      sugar: '5g',
      sodium: '1380mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'homemade-beef-ramen',
    title: 'Homemade Beef Ramen Recipe',
    cardTitle: 'Homemade Beef Ramen',
    description:
      "This homemade beef ramen leans on seared beef and a soy-and-beef-broth base for a rich, restaurant-style bowl at home. Thin-sliced beef cooks in minutes right in the hot broth, so it stays tender instead of overcooked.",
    image: pickStockPhoto('homemade-beef-ramen'),
    rating: 4.5,
    reviewCount: 76,
    prepTime: '15 minutes',
    cookTime: '30 minutes',
    totalTime: '45 minutes',
    baseServings: 4,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '1', unit: 'lb', metricAmount: '450', metricUnit: 'g', item: 'thin-sliced beef sirloin or ribeye', note: 'freeze 20 minutes first for easier slicing' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'vegetable oil' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'grated ginger' },
      { amount: '3', unit: 'cloves', metricAmount: '3', metricUnit: 'cloves', item: 'garlic, minced' },
      { amount: '6', unit: 'cups', metricAmount: '1420', metricUnit: 'ml', item: 'beef stock' },
      { amount: '3', unit: 'tablespoons', metricAmount: '45', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'oyster sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'mirin' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'g', item: 'brown sugar' },
      { amount: '8', unit: 'ounces', metricAmount: '225', metricUnit: 'g', item: 'ramen noodles' },
      { amount: '1', unit: 'cup', metricAmount: '100', metricUnit: 'g', item: 'shiitake mushrooms, sliced' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'scallions, thinly sliced' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'ml', item: 'sesame oil, for finishing' },
    ],
    steps: [
      { text: 'Pat the beef dry and season lightly with salt and pepper. Heat the oil in a large pot over high heat and sear the beef in batches for 30–45 seconds per side, until browned but still rare in the center. Remove and set aside.' },
      { text: 'Reduce heat to medium. Add the ginger and garlic to the same pot and sauté 30 seconds, scraping up the browned bits.' },
      { text: 'Pour in the beef stock, soy sauce, oyster sauce, mirin, and brown sugar. Bring to a simmer.' },
      { text: 'Add the sliced mushrooms and simmer for 10 minutes to build flavor.' },
      { text: 'Meanwhile, cook the ramen noodles separately according to the package instructions, then drain.' },
      { text: 'Return the seared beef (and any resting juices) to the pot just long enough to warm through, about 1 minute — don\'t let it overcook.' },
      { text: 'Divide the noodles among bowls, ladle the broth, beef, and mushrooms over top, drizzle with sesame oil, and top with scallions.' },
    ],
    whatToAdd: [
      { title: 'Vegetables', text: 'Bok choy, napa cabbage, or bean sprouts add crunch and balance the richness of the beef broth.' },
      { title: 'Egg', text: 'A soft-boiled or fried egg on top adds richness and turns this into an even heartier meal.' },
      { title: 'Heat', text: 'A drizzle of chili oil or a spoonful of gochujang gives the broth a spicy kick that pairs well with beef.' },
      { title: 'Extra richness', text: 'A small pat of butter stirred into the broth at the end adds a silky, restaurant-style finish.' },
    ],
    nutrition: {
      calories: 510,
      protein: '34g',
      carbs: '46g',
      fat: '19g',
      fiber: '2g',
      sugar: '6g',
      sodium: '1520mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'homemade-shrimp-ramen',
    title: 'Homemade Shrimp Ramen Recipe',
    cardTitle: 'Homemade Shrimp Ramen',
    description:
      "This homemade shrimp ramen uses the shrimp shells to build a quick, seafood-forward broth, then finishes with the shrimp themselves cooked just until pink and tender. It's a lighter, faster take on ramen that's ready in about 35 minutes.",
    image: pickStockPhoto('homemade-shrimp-ramen'),
    rating: 4.3,
    reviewCount: 61,
    prepTime: '15 minutes',
    cookTime: '20 minutes',
    totalTime: '35 minutes',
    baseServings: 4,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '1', unit: 'lb', metricAmount: '450', metricUnit: 'g', item: 'large shrimp, peeled and deveined', note: 'reserve the shells' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'sesame oil' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'grated ginger' },
      { amount: '2', unit: 'cloves', metricAmount: '2', metricUnit: 'cloves', item: 'garlic, minced' },
      { amount: '5', unit: 'cups', metricAmount: '1180', metricUnit: 'ml', item: 'seafood or chicken stock' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'fish sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'g', item: 'white miso paste' },
      { amount: '8', unit: 'ounces', metricAmount: '225', metricUnit: 'g', item: 'ramen noodles' },
      { amount: '1', unit: 'cup', metricAmount: '100', metricUnit: 'g', item: 'baby bok choy, halved' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'scallions, thinly sliced' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'ml', item: 'chili oil', note: 'optional' },
    ],
    steps: [
      { text: 'Heat the sesame oil in a pot over medium heat. Add the reserved shrimp shells and toast for 2–3 minutes, stirring, until fragrant and pink.' },
      { text: 'Add the ginger and garlic and sauté 30 seconds.' },
      { text: 'Pour in the stock and bring to a simmer. Let it simmer for 10 minutes to infuse with the shrimp shells, then strain out the shells and return the broth to the pot.' },
      { text: 'Stir the soy sauce and fish sauce into the broth. Whisk the miso with a splash of hot broth until smooth, then stir it back in.' },
      { text: 'Add the bok choy and simmer 2 minutes, then add the shrimp and cook for 2–3 minutes, just until pink and opaque — don\'t overcook.' },
      { text: 'Meanwhile, cook the ramen noodles separately according to the package instructions, then drain.' },
      { text: 'Divide the noodles among bowls, ladle the broth, shrimp, and bok choy over top, and finish with scallions and chili oil if using.' },
    ],
    whatToAdd: [
      { title: 'Extra seafood', text: 'Scallops or thin slices of fish fillet cook well alongside the shrimp for a fuller seafood bowl.' },
      { title: 'Vegetables', text: 'Corn, mushrooms, and bean sprouts all work well and add texture.' },
      { title: 'Richness', text: 'A soft-boiled egg or a small drizzle of coconut milk gives the broth a rounder, richer finish.' },
      { title: 'Heat', text: 'Sriracha or chili crisp stirred in at the table lets everyone adjust the spice to taste.' },
    ],
    nutrition: {
      calories: 380,
      protein: '28g',
      carbs: '44g',
      fat: '9g',
      fiber: '2g',
      sugar: '3g',
      sodium: '1390mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'homemade-creamy-chicken-ramen',
    title: 'Homemade Creamy Chicken Ramen Recipe',
    cardTitle: 'Homemade Creamy Chicken Ramen',
    description:
      "This creamy chicken ramen gets its silky, tonkotsu-style body from simmered chicken and a splash of milk — a shortcut for the rich, opaque broth that usually takes 12+ hours to make from pork bones. It's indulgent, cozy, and ready well within a weeknight.",
    image: pickStockPhoto('homemade-creamy-chicken-ramen'),
    rating: 4.7,
    reviewCount: 103,
    prepTime: '10 minutes',
    cookTime: '45 minutes',
    totalTime: '55 minutes',
    baseServings: 4,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'butter' },
      { amount: '1.5', unit: 'lbs', metricAmount: '680', metricUnit: 'g', item: 'boneless, skinless chicken thighs' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'grated ginger' },
      { amount: '3', unit: 'cloves', metricAmount: '3', metricUnit: 'cloves', item: 'garlic, minced' },
      { amount: '5', unit: 'cups', metricAmount: '1180', metricUnit: 'ml', item: 'chicken stock' },
      { amount: '1', unit: 'cup', metricAmount: '240', metricUnit: 'ml', item: 'whole milk' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'g', item: 'white miso paste' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'sesame paste (tahini works too)' },
      { amount: '8', unit: 'ounces', metricAmount: '225', metricUnit: 'g', item: 'ramen noodles' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'soft-boiled eggs, halved' },
      { amount: '1', unit: 'cup', metricAmount: '150', metricUnit: 'g', item: 'corn kernels' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'scallions, thinly sliced' },
    ],
    steps: [
      { text: 'Melt the butter in a pot over medium heat. Add the chicken thighs and cook for 5–6 minutes per side, until golden and cooked through. Remove and set aside.' },
      { text: 'Add the ginger and garlic to the same pot and sauté 30 seconds, scraping up the browned bits.' },
      { text: 'Pour in the chicken stock and bring to a simmer. Let it simmer for 20 minutes to concentrate the flavor.' },
      { text: 'Stir in the milk, then whisk in the miso paste, soy sauce, and sesame paste until fully dissolved — this is what gives the broth its silky, opaque body.' },
      { text: 'Simmer gently for another 5 minutes; don\'t let it come to a hard boil once the milk is in, or it can separate.' },
      { text: 'Slice the cooked chicken while the broth finishes simmering.' },
      { text: 'Cook the ramen noodles separately according to the package instructions, then drain.' },
      { text: 'Divide the noodles among bowls, ladle the creamy broth over top, and arrange the sliced chicken, egg, corn, and scallions on top.' },
    ],
    whatToAdd: [
      { title: 'Extra creaminess', text: 'A drizzle of coconut milk or an extra spoonful of sesame paste makes the broth even richer.' },
      { title: 'Heat', text: 'Chili oil or a spoonful of gochujang cuts through the richness nicely.' },
      { title: 'Vegetables', text: 'Spinach or bean sprouts added at the end add freshness against the creamy broth.' },
      { title: 'Crunch', text: 'Toasted sesame seeds or crushed peanuts on top add texture.' },
    ],
    nutrition: {
      calories: 560,
      protein: '33g',
      carbs: '50g',
      fat: '24g',
      fiber: '2g',
      sugar: '7g',
      sodium: '1460mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'pork-broth-ramen',
    title: 'Pork Broth Ramen Recipe',
    cardTitle: 'Pork Broth Ramen',
    description:
      "A rich, deeply savory pork broth built from pork bones and a chashu-style shoulder roast, simmered low and slow until the broth turns cloudy and full-bodied. This is the broth to make when you want real ramen-shop flavor without needing a 12-hour tonkotsu boil.",
    image: pickStockPhoto('pork-broth-ramen'),
    rating: 4.6,
    reviewCount: 88,
    prepTime: '20 minutes',
    cookTime: '3 hours 30 minutes',
    totalTime: '3 hours 50 minutes',
    baseServings: 6,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '3', unit: 'lbs', metricAmount: '1.4', metricUnit: 'kg', item: 'pork neck bones or ham hocks' },
      { amount: '1', unit: 'lb', metricAmount: '450', metricUnit: 'g', item: 'pork shoulder, in one piece' },
      { amount: '1', unit: '', metricAmount: '1', metricUnit: '', item: 'onion, halved' },
      { amount: '1', unit: 'head', metricAmount: '1', metricUnit: 'head', item: 'garlic, halved crosswise' },
      { amount: '2', unit: 'inches', metricAmount: '5', metricUnit: 'cm', item: 'ginger, sliced' },
      { amount: '3', unit: '', metricAmount: '3', metricUnit: '', item: 'scallions, whole' },
      { amount: '12', unit: 'cups', metricAmount: '2.8', metricUnit: 'liters', item: 'water' },
      { amount: '3', unit: 'tablespoons', metricAmount: '45', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'mirin' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'g', item: 'salt, plus more to taste' },
    ],
    steps: [
      { text: 'Place the pork bones in a large pot, cover with cold water, and bring to a boil. Boil hard for 5 minutes — this draws out impurities that would otherwise cloud and muddy the broth\'s flavor.' },
      { text: 'Drain the bones and rinse them well under cold water, scrubbing off any scum. Rinse out the pot too.' },
      { text: 'Return the bones to the clean pot along with the pork shoulder, onion, garlic, ginger, and scallions. Add the 12 cups of water.' },
      { text: 'Bring to a boil, then reduce to a low, steady simmer. Skim off any foam that rises in the first 20 minutes.' },
      { text: 'Simmer uncovered for 2 hours, then remove the pork shoulder (it should be tender) and set it aside to cool and slice later for chashu-style topping.' },
      { text: 'Continue simmering the bones for another 1.5 hours, until the broth has reduced and turned rich and slightly cloudy.' },
      { text: 'Strain the broth through a fine mesh sieve, discarding the solids. Stir in the soy sauce, mirin, and salt, tasting and adjusting as you go.' },
      { text: 'Serve hot over cooked ramen noodles, topped with sliced pork shoulder and your favorite toppings.' },
    ],
    whatToAdd: [
      { title: 'Toppings', text: 'Sliced chashu (from the pork shoulder), a soft-boiled egg, scallions, bamboo shoots, and nori make a classic bowl.' },
      { title: 'Deeper flavor', text: 'Roast the pork bones at 425°F (220°C) for 30 minutes before boiling for a richer, more roasted broth flavor.' },
      { title: 'Shortcut', text: 'A pressure cooker cuts the simmer time to about 90 minutes total while still producing a rich broth.' },
      { title: 'Heat', text: 'A spoonful of chili oil or rayu stirred in at the table adds a spicy contrast to the rich broth.' },
    ],
    nutrition: {
      calories: 340,
      protein: '22g',
      carbs: '4g',
      fat: '26g',
      fiber: '0g',
      sugar: '1g',
      sodium: '1280mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'chicken-broth-ramen',
    title: 'Chicken Broth Ramen Recipe',
    cardTitle: 'Chicken Broth Ramen',
    description:
      "A clean, savory chicken broth (chintan-style) built from chicken wings and aromatics — lighter than a pork-based broth but still deeply flavorful. This is the broth that works for almost any ramen topping combination you have on hand.",
    image: pickStockPhoto('chicken-broth-ramen'),
    rating: 4.5,
    reviewCount: 72,
    prepTime: '15 minutes',
    cookTime: '2 hours',
    totalTime: '2 hours 15 minutes',
    baseServings: 6,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '3', unit: 'lbs', metricAmount: '1.4', metricUnit: 'kg', item: 'chicken wings and backs' },
      { amount: '1', unit: '', metricAmount: '1', metricUnit: '', item: 'onion, halved' },
      { amount: '4', unit: 'cloves', metricAmount: '4', metricUnit: 'cloves', item: 'garlic, smashed' },
      { amount: '2', unit: 'inches', metricAmount: '5', metricUnit: 'cm', item: 'ginger, sliced' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'dried shiitake mushrooms' },
      { amount: '1', unit: 'piece', metricAmount: '1', metricUnit: 'piece', item: 'kombu (dried kelp), about 4 inches' },
      { amount: '12', unit: 'cups', metricAmount: '2.8', metricUnit: 'liters', item: 'water' },
      { amount: '3', unit: 'tablespoons', metricAmount: '45', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'mirin' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'g', item: 'salt, plus more to taste' },
    ],
    steps: [
      { text: 'Rinse the chicken wings and backs under cold water. Place them in a large pot, cover with cold water, and bring to a boil for 3 minutes to remove impurities.' },
      { text: 'Drain and rinse the chicken pieces well, then rinse out the pot.' },
      { text: 'Return the chicken to the clean pot with the onion, garlic, ginger, shiitake mushrooms, and kombu. Add the 12 cups of water.' },
      { text: 'Bring to a boil, then reduce to a gentle simmer. Skim any foam from the surface during the first 20 minutes.' },
      { text: 'Simmer uncovered, without stirring too vigorously, for about 1.5 hours, until the broth is fragrant and golden.' },
      { text: 'Strain the broth through a fine mesh sieve, discarding the solids (or reserve the chicken meat for another use, like toppings).' },
      { text: 'Stir in the soy sauce, mirin, and salt, tasting and adjusting the seasoning.' },
      { text: 'Serve hot over cooked ramen noodles with your favorite toppings.' },
    ],
    whatToAdd: [
      { title: 'Toppings', text: 'Shredded chicken (from the broth), a soft-boiled egg, corn, scallions, and menma (fermented bamboo shoots) are classic.' },
      { title: 'Richer body', text: 'Simmer a few chicken feet alongside the wings for extra collagen and a fuller mouthfeel.' },
      { title: 'Umami boost', text: 'A splash of the kombu\'s soaking liquid or a small piece of dried bonito (katsuobushi) added in the last 10 minutes deepens the broth.' },
      { title: 'Heat', text: 'White pepper or a drizzle of chili oil brightens up this milder broth nicely.' },
    ],
    nutrition: {
      calories: 260,
      protein: '24g',
      carbs: '3g',
      fat: '16g',
      fiber: '0g',
      sugar: '1g',
      sodium: '1190mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'shrimp-broth-ramen',
    title: 'Shrimp Broth Ramen Recipe',
    cardTitle: 'Shrimp Broth Ramen',
    description:
      "A quick, seafood-forward broth built entirely from shrimp shells and heads — nothing goes to waste. This broth comes together in under an hour and delivers a briny, umami-rich base that's lighter than a meat-based broth but just as satisfying.",
    image: 'https://www.countrysidecravings.com/wp-content/uploads/2023/05/Shrimp-Ramen.jpeg',
    rating: 4.3,
    reviewCount: 54,
    prepTime: '10 minutes',
    cookTime: '40 minutes',
    totalTime: '50 minutes',
    baseServings: 4,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '1', unit: 'lb', metricAmount: '450', metricUnit: 'g', item: 'shrimp shells and heads', note: 'from about 2 lbs whole shrimp' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'vegetable oil' },
      { amount: '1', unit: '', metricAmount: '1', metricUnit: '', item: 'onion, chopped' },
      { amount: '3', unit: 'cloves', metricAmount: '3', metricUnit: 'cloves', item: 'garlic, smashed' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'tomato paste' },
      { amount: '8', unit: 'cups', metricAmount: '1.9', metricUnit: 'liters', item: 'water' },
      { amount: '1', unit: 'piece', metricAmount: '1', metricUnit: 'piece', item: 'kombu (dried kelp), about 4 inches' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'fish sauce' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'g', item: 'salt, to taste' },
    ],
    steps: [
      { text: 'Heat the oil in a large pot over medium-high heat. Add the shrimp shells and heads and cook for 4–5 minutes, stirring often, until they turn bright pink and fragrant.' },
      { text: 'Add the onion and garlic and cook for 3 minutes, until softened.' },
      { text: 'Stir in the tomato paste and cook for 1 minute to deepen its flavor.' },
      { text: 'Add the water and kombu, and bring to a boil. Reduce to a simmer and cook uncovered for 25–30 minutes, letting the shells continue to release flavor.' },
      { text: 'Strain the broth through a fine mesh sieve, pressing on the solids to extract as much liquid as possible, then discard the shells.' },
      { text: 'Stir in the soy sauce, fish sauce, and salt, tasting and adjusting seasoning as needed.' },
      { text: 'Serve hot over cooked ramen noodles with your favorite toppings.' },
    ],
    whatToAdd: [
      { title: 'Toppings', text: 'The peeled shrimp themselves (quickly sautéed or poached), corn, bok choy, and a soft-boiled egg pair perfectly.' },
      { title: 'Richness', text: 'A splash of coconut milk or a small pat of butter stirred in at the end rounds out the briny broth.' },
      { title: 'Extra depth', text: 'Toast the shrimp shells a bit longer, until you see some browning on the pot, before adding the water for a deeper roasted-seafood flavor.' },
      { title: 'Heat', text: 'Chili oil, sambal, or a spoonful of gochujang adds a spicy kick that pairs especially well with shrimp.' },
    ],
    nutrition: {
      calories: 180,
      protein: '14g',
      carbs: '5g',
      fat: '9g',
      fiber: '1g',
      sugar: '2g',
      sodium: '1240mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'spicy-chicken-broth-ramen',
    title: 'Spicy Chicken Broth Ramen Recipe',
    cardTitle: 'Spicy Chicken Broth Ramen',
    description:
      "This spicy chicken broth takes a savory chicken base and builds real heat into it with chili oil, gochujang, and doubanjiang — the kind of broth that warms you up from the first sip, with heat you can dial up or down to taste.",
    image: pickStockPhoto('spicy-chicken-broth-ramen'),
    rating: 4.5,
    reviewCount: 69,
    prepTime: '15 minutes',
    cookTime: '1 hour',
    totalTime: '1 hour 15 minutes',
    baseServings: 4,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'vegetable oil' },
      { amount: '2', unit: 'lbs', metricAmount: '900', metricUnit: 'g', item: 'chicken thighs or wings' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'grated ginger' },
      { amount: '4', unit: 'cloves', metricAmount: '4', metricUnit: 'cloves', item: 'garlic, minced' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'g', item: 'doubanjiang (spicy fermented bean paste)' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'g', item: 'gochujang' },
      { amount: '8', unit: 'cups', metricAmount: '1.9', metricUnit: 'liters', item: 'chicken stock' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'chili oil, plus more to taste' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'ml', item: 'rice vinegar' },
    ],
    steps: [
      { text: 'Heat the oil in a large pot over medium-high heat. Season the chicken and sear on both sides until golden, about 3–4 minutes per side. Remove and set aside.' },
      { text: 'Reduce heat to medium. Add the ginger and garlic and sauté 30 seconds, until fragrant.' },
      { text: 'Add the doubanjiang and gochujang and cook for 1–2 minutes, stirring constantly, until the oil turns red and the pastes smell toasted — this step builds the base of the heat.' },
      { text: 'Pour in the chicken stock, scraping up any browned bits from the bottom of the pot. Return the chicken to the pot.' },
      { text: 'Bring to a boil, then reduce to a simmer. Cover and cook for 35–40 minutes, until the chicken is cooked through and tender.' },
      { text: 'Remove the chicken, shred or slice it, and set aside.' },
      { text: 'Stir the soy sauce, chili oil, and rice vinegar into the broth, tasting and adjusting the heat level to your preference.' },
      { text: 'Serve hot over cooked ramen noodles, topped with the chicken.' },
    ],
    whatToAdd: [
      { title: 'More heat', text: 'Extra chili oil, sliced fresh chilies, or a spoonful more gochujang all let you push the spice further.' },
      { title: 'Cooling contrast', text: 'A soft-boiled egg, corn, or a small drizzle of sesame oil helps balance the heat.' },
      { title: 'Vegetables', text: 'Bean sprouts, bok choy, and mushrooms hold up well simmered briefly in the spicy broth.' },
      { title: 'Numbing spice', text: 'A pinch of ground Sichuan peppercorn added with the pastes gives this a mala, tingly heat instead of straight chili heat.' },
    ],
    nutrition: {
      calories: 390,
      protein: '30g',
      carbs: '8g',
      fat: '25g',
      fiber: '1g',
      sugar: '3g',
      sodium: '1540mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'tonkotsu-ramen-broth',
    title: 'Tonkotsu Ramen Broth Recipe',
    cardTitle: 'Tonkotsu Ramen Broth',
    description:
      "Real tonkotsu is a long-haul project — pork bones boiled hard for hours until they break down into a broth that's thick, milky-white, and intensely rich. It takes patience, but the process itself is simple, and the payoff is a broth that tastes like it came straight from a ramen shop.",
    image: pickStockPhoto('tonkotsu-ramen-broth'),
    rating: 4.8,
    reviewCount: 142,
    prepTime: '20 minutes',
    cookTime: '9 hours',
    totalTime: '9 hours 20 minutes',
    baseServings: 8,
    servingsLabel: 'heaping 1-cup servings',
    ingredients: [
      { amount: '4', unit: 'lbs', metricAmount: '1.8', metricUnit: 'kg', item: 'pork trotters (feet), split' },
      { amount: '2', unit: 'lbs', metricAmount: '900', metricUnit: 'g', item: 'pork neck bones' },
      { amount: '1', unit: '', metricAmount: '1', metricUnit: '', item: 'whole head garlic, halved' },
      { amount: '1', unit: '', metricAmount: '1', metricUnit: '', item: 'onion, halved' },
      { amount: '3', unit: 'inches', metricAmount: '8', metricUnit: 'cm', item: 'ginger, sliced' },
      { amount: '16', unit: 'cups', metricAmount: '3.8', metricUnit: 'liters', item: 'water, plus more as needed' },
      { amount: '3', unit: 'tablespoons', metricAmount: '45', metricUnit: 'ml', item: 'soy sauce (for the tare)' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'mirin (for the tare)' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'g', item: 'salt, plus more to taste' },
    ],
    steps: [
      { text: 'Place the trotters and neck bones in a very large pot, cover with cold water, and bring to a hard boil for 10 minutes. This first boil draws out blood and impurities that would otherwise cloud and dull the broth.' },
      { text: 'Drain the bones and rinse them thoroughly under cold water, scrubbing off any remaining scum with a brush. Rinse the pot clean as well.' },
      { text: 'Return the bones to the clean pot with the garlic, onion, and ginger. Add the 16 cups of water — the bones should be fully submerged.' },
      { text: 'Bring to a rolling boil and keep it at a hard, rolling boil (not a gentle simmer) for the entire cook time — the vigorous boiling is what emulsifies the collagen and fat into the water, turning the broth cloudy and milky-white.' },
      { text: 'Boil for 8–9 hours, checking every hour or two and topping up with hot water as it reduces, keeping the bones covered.' },
      { text: 'The broth is ready when it\'s opaque, pale ivory, and coats the back of a spoon. Strain through a fine mesh sieve, pressing on the bones to extract every bit of collagen, then discard the solids.' },
      { text: 'To season a bowl, whisk together the soy sauce, mirin, and salt in each serving bowl, then ladle the hot tonkotsu broth over top and stir to combine before adding noodles and toppings.' },
    ],
    whatToAdd: [
      { title: 'Toppings', text: 'Chashu pork, a marinated soft-boiled egg (ajitama), wood ear mushrooms, pickled ginger (beni shoga), and scallions are the classic tonkotsu toppings.' },
      { title: 'Shortcut', text: 'A pressure cooker can produce a similarly rich, milky broth in about 2 hours at high pressure instead of a 9-hour open boil.' },
      { title: 'Extra richness', text: 'Blend a ladleful of the cooked bone marrow and fat back into the strained broth for an even thicker, richer texture.' },
      { title: 'Heat', text: 'A spoonful of spicy miso (kara miso) or rayu chili oil turns this into a spicy tonkotsu bowl.' },
    ],
    nutrition: {
      calories: 410,
      protein: '20g',
      carbs: '2g',
      fat: '35g',
      fiber: '0g',
      sugar: '1g',
      sodium: '980mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'homemade-egg-and-ramen',
    title: 'Homemade Egg and Ramen Recipe',
    cardTitle: 'Egg and Ramen',
    description: 'A comforting, egg-forward ramen bowl built around a silky soft-boiled marinated egg and a quick savory broth — ready in about 30 minutes.',
    image: pickStockPhoto('homemade-egg-and-ramen'),
    rating: 4.5,
    reviewCount: 61,
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    totalTime: '30 minutes',
    baseServings: 2,
    servingsLabel: '1 bowl servings',
    ingredients: [
      { amount: '4', unit: 'large', metricAmount: '4', metricUnit: 'large', item: 'eggs', note: 'for marinating and soft-boiling' },
      { amount: '1/4', unit: 'cup', metricAmount: '60', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'mirin' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'sugar' },
      { amount: '4', unit: 'cups', metricAmount: '950', metricUnit: 'ml', item: 'chicken broth' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'soy sauce', note: 'for the broth' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'ml', item: 'sesame oil' },
      { amount: '2', unit: 'servings', metricAmount: '2', metricUnit: 'servings', item: 'ramen noodles', note: 'fresh or dried' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'scallions, sliced' },
      { amount: '1', unit: 'sheet', metricAmount: '1', metricUnit: 'sheet', item: 'nori, cut into strips' },
    ],
    steps: [
      { text: 'Bring a pot of water to a boil and gently lower in the eggs. Boil for exactly 7 minutes for a jammy yolk, then transfer immediately to an ice bath.' },
      { text: 'Once cool, peel the eggs carefully and place them in a small bag or container with the soy sauce, mirin, and sugar. Marinate for at least 2 hours, or overnight for a deeper color and flavor.' },
      { text: 'In a saucepan, bring the chicken broth to a simmer with the soy sauce and sesame oil.' },
      { text: 'Cook the ramen noodles separately according to package instructions, then divide between bowls.' },
      { text: 'Ladle the hot broth over the noodles, then halve a marinated egg and place it on top of each bowl.' },
      { text: 'Garnish with sliced scallions and nori strips before serving.' },
    ],
    whatToAdd: [
      { title: 'Extra protein', text: 'Add sliced chashu pork or grilled chicken alongside the egg for a heartier bowl.' },
      { title: 'Umami boost', text: 'A small spoonful of miso paste whisked into the broth deepens the flavor.' },
      { title: 'Crunch', text: 'Bean sprouts or thinly sliced cabbage add texture and freshness.' },
      { title: 'Spice', text: 'A drizzle of chili oil or a shake of shichimi togarashi adds heat.' },
    ],
    nutrition: {
      calories: 420,
      protein: '22g',
      carbs: '48g',
      fat: '14g',
      fiber: '2g',
      sugar: '6g',
      sodium: '1580mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'miso-ramen',
    title: 'Miso Ramen Recipe',
    cardTitle: 'Miso Ramen',
    description: 'A rich, nutty miso ramen with a savory-sweet broth, tender noodles, and classic toppings — one of the most popular ramen styles to make at home.',
    image: 'https://cdn.justonecookbook.com/spai/q_glossy+ret_img+to_auto/www.justonecookbook.com/wp-content/uploads/2025/10/Miso-Ramen-7281-II-1365x2048.jpg',
    gallery: [
      'https://cdn.justonecookbook.com/spai/q_glossy+ret_img+to_auto/www.justonecookbook.com/wp-content/uploads/2025/10/Miso-Ramen-7281-II-1365x2048.jpg',
      'https://cdn.justonecookbook.com/spai/q_glossy+ret_img+to_auto/www.justonecookbook.com/wp-content/uploads/2025/10/Miso-Ramen-7272-III-1365x2048.jpg',
    ],
    rating: 4.6,
    reviewCount: 97,
    prepTime: '15 minutes',
    cookTime: '30 minutes',
    totalTime: '45 minutes',
    baseServings: 4,
    servingsLabel: '1 bowl servings',
    ingredients: [
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'sesame oil' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'garlic, minced' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'ginger, minced' },
      { amount: '1/2', unit: 'cup', metricAmount: '120', metricUnit: 'ml', item: 'ground pork or chicken', note: 'optional, for extra body' },
      { amount: '1/3', unit: 'cup', metricAmount: '80', metricUnit: 'ml', item: 'white or yellow miso paste' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'mirin' },
      { amount: '6', unit: 'cups', metricAmount: '1420', metricUnit: 'ml', item: 'chicken or pork broth' },
      { amount: '4', unit: 'servings', metricAmount: '4', metricUnit: 'servings', item: 'ramen noodles' },
      { amount: '1', unit: 'cup', metricAmount: '90', metricUnit: 'g', item: 'bean sprouts' },
      { amount: '1', unit: 'cup', metricAmount: '90', metricUnit: 'g', item: 'corn kernels', note: 'a classic miso ramen topping' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'soft-boiled eggs, halved' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'g', item: 'butter', note: 'traditional Sapporo-style topping' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'scallions, sliced' },
    ],
    steps: [
      { text: 'Heat the sesame oil in a large pot over medium heat. Add the garlic and ginger and cook until fragrant, about 30 seconds.' },
      { text: 'If using, add the ground pork or chicken and cook until browned, breaking it up with a spoon.' },
      { text: 'Stir in the miso paste, soy sauce, and mirin, cooking for 1-2 minutes until the miso is fragrant and slightly caramelized.' },
      { text: 'Pour in the broth, stir to dissolve the miso completely, and bring to a gentle simmer for 15 minutes.' },
      { text: 'Cook the ramen noodles separately according to package instructions, then divide between bowls.' },
      { text: 'Ladle the hot miso broth over the noodles.' },
      { text: 'Top each bowl with bean sprouts, corn, a halved soft-boiled egg, a pat of butter, and sliced scallions.' },
    ],
    whatToAdd: [
      { title: 'Toppings', text: 'Chashu pork, wood ear mushrooms, or nori strips all pair well with miso broth.' },
      { title: 'Vegetarian option', text: 'Skip the meat and use vegetable broth for a fully vegetarian bowl — the miso still delivers plenty of depth.' },
      { title: 'Richness', text: 'A spoonful of rendered pork fat or a splash of cream stirred into the broth makes it extra silky.' },
      { title: 'Regional twist', text: 'Add a spoonful of doubanjiang (spicy bean paste) for a Sapporo-style kick.' },
    ],
    nutrition: {
      calories: 520,
      protein: '24g',
      carbs: '58g',
      fat: '20g',
      fiber: '3g',
      sugar: '7g',
      sodium: '1720mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
  {
    slug: 'spicy-miso-ramen',
    title: 'Spicy Miso Ramen Recipe',
    cardTitle: 'Spicy Miso Ramen',
    description: 'A fiery twist on classic miso ramen, with chili oil and doubanjiang stirred into a rich, nutty broth for serious heat and depth.',
    image: pickStockPhoto('spicy-miso-ramen'),
    rating: 4.6,
    reviewCount: 83,
    prepTime: '15 minutes',
    cookTime: '30 minutes',
    totalTime: '45 minutes',
    baseServings: 4,
    servingsLabel: '1 bowl servings',
    ingredients: [
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'sesame oil' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'garlic, minced' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'ginger, minced' },
      { amount: '1/2', unit: 'cup', metricAmount: '120', metricUnit: 'ml', item: 'ground pork', note: 'optional, for extra body' },
      { amount: '1/3', unit: 'cup', metricAmount: '80', metricUnit: 'ml', item: 'white or red miso paste' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'doubanjiang', note: 'spicy fermented bean paste' },
      { amount: '1', unit: 'tablespoon', metricAmount: '15', metricUnit: 'ml', item: 'chili oil, plus more for serving' },
      { amount: '2', unit: 'tablespoons', metricAmount: '30', metricUnit: 'ml', item: 'soy sauce' },
      { amount: '6', unit: 'cups', metricAmount: '1420', metricUnit: 'ml', item: 'chicken or pork broth' },
      { amount: '4', unit: 'servings', metricAmount: '4', metricUnit: 'servings', item: 'ramen noodles' },
      { amount: '1', unit: 'cup', metricAmount: '90', metricUnit: 'g', item: 'bean sprouts' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'soft-boiled eggs, halved' },
      { amount: '2', unit: '', metricAmount: '2', metricUnit: '', item: 'scallions, sliced' },
      { amount: '1', unit: 'teaspoon', metricAmount: '5', metricUnit: 'ml', item: 'toasted sesame seeds' },
    ],
    steps: [
      { text: 'Heat the sesame oil in a large pot over medium heat. Add the garlic and ginger and cook until fragrant, about 30 seconds.' },
      { text: 'If using, add the ground pork and cook until browned, breaking it up with a spoon.' },
      { text: 'Stir in the miso paste, doubanjiang, and chili oil, cooking for 1-2 minutes until fragrant and slightly darkened.' },
      { text: 'Add the soy sauce and broth, stir to dissolve the miso completely, and bring to a gentle simmer for 15 minutes.' },
      { text: 'Taste and add more chili oil or doubanjiang for extra heat, if desired.' },
      { text: 'Cook the ramen noodles separately according to package instructions, then divide between bowls.' },
      { text: 'Ladle the hot spicy miso broth over the noodles.' },
      { text: 'Top each bowl with bean sprouts, a halved soft-boiled egg, scallions, and toasted sesame seeds. Finish with an extra drizzle of chili oil.' },
    ],
    whatToAdd: [
      { title: 'Extra heat', text: 'Add sliced fresh Thai chilies or a spoonful of la-yu chili oil for more fire.' },
      { title: 'Toppings', text: 'Chashu pork, corn, and a pat of butter balance out the spice nicely.' },
      { title: 'Cooling contrast', text: 'A few slices of cucumber or a dollop of Kewpie mayo on the side helps temper the heat.' },
      { title: 'Deeper flavor', text: 'Toast the doubanjiang and miso in the oil a little longer for a more caramelized, complex broth.' },
    ],
    nutrition: {
      calories: 540,
      protein: '25g',
      carbs: '58g',
      fat: '22g',
      fiber: '3g',
      sugar: '6g',
      sodium: '1840mg',
    },
    category: 'Recipes',
    date: 'July 9, 2026',
  },
]

export function getRecipe(slug: string): Recipe | undefined {
  return RECIPES.find((r) => r.slug === slug)
}

export function getAllRecipes(): Recipe[] {
  return RECIPES
}
